name: CI — macOS build (dotnet SDK projects)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-macos:
    name: Build (macOS, dotnet SDK projects)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore and build SDK-style projects
        run: |
          set -e
          echo "Finding SDK-style projects (look for '<Project Sdk' in .csproj)..."
          sdk_projects=$(grep -l "<Project .*Sdk=" -R --include="*.csproj" || true)
          if [ -z "$sdk_projects" ]; then
            echo "No SDK-style projects found."
            exit 0
          fi
          echo "SDK projects found:"
          echo "$sdk_projects"
          for p in $sdk_projects; do
            # skip projects that reference legacy .NET Framework projects which cannot be built on macOS
            if grep -q "<ProjectReference.*Lexplosion.Core" "$p" || grep -q "<ProjectReference.*Lexplosion.UI.WPF" "$p"; then
              echo "Skipping $p — references legacy .NET Framework projects"
              continue
            fi
            echo "dotnet restore $p"
            dotnet restore "$p"
            echo "dotnet build $p"
            dotnet build "$p" --configuration Release
          done

      - name: Run tests if test project exists and is compatible
        run: |
          set -e
          TEST_PROJ=src/Lexplosion.Tests/Lexplosion.Tests.csproj
          if [ -f "$TEST_PROJ" ]; then
            if grep -q "<ProjectReference.*Lexplosion.Core" "$TEST_PROJ" || grep -q "<ProjectReference.*Lexplosion.UI.WPF" "$TEST_PROJ"; then
              echo "Skipping tests on macOS — test project references legacy .NET Framework projects"
              exit 0
            fi
            dotnet test "$TEST_PROJ" --configuration Release
          else
            echo "No test project found"
          fi
